### ISSUE TITLE
CSS Tools | SkyBlog

### ISSUE THREAD

**Issue by Flysky12138** [Flysky12138/blog#9]
https://blog.flysky.xyz/2021/09/05/CSS-Tools/ 

 CSS 样式属性的调整、预览工具

**Comment by Flysky12138** [comment]
引入的iframe中加入了
```CSS
*{
  touch-action: none;
}
```
因此，在手机设备上，虚线区域内不能触摸滑动屏幕。
